config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :staffs, controllers: {
    registrations: "staffs/registrations"
  }

  devise_for :students, controllers: {
    registrations: "students/registrations",
    sessions: "students/sessions",
    passwords: "students/passwords",
    confirmations: "students/confirmations" }

  resources :students, only: [] do
    resource :dashboards, only: :show, controller: 'students/dashboards'
  end

  root "homes#index"

  get 'dashboards' => 'staffs/dashboards#dashboards'

  resources :courses

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:creator, :accountant, :human_resource_manager]
  enum salary_period: [:per_day, :per_month]

  has_attached_file :avatar, styles: { large: "400x400>", medium: "200x200>", small: "100x100>", thumb: "40x40>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  has_many :courses, dependent: :destroy

  def s3_credentials
    {:bucket => "linhly", :access_key_id => ENV['s3_access_key_id'], :secret_access_key => ENV['s3_secret_access_key']}
  end

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/staffs/dashboards_controller.rb
module Staffs
  class DashboardsController < ApplicationController
    def dashboards
      @courses = filtered_courses
    end

    private

    def filtered_courses
      Course.all
    end
  end
end

app/controllers/staffs/registrations_controller.rb
class Staffs::RegistrationsController < Devise::RegistrationsController
  # prepend_before_filter :require_no_authentication, only: [:edit, :update, :destroy ]
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/staffs/creators/_dashboard.html.haml
- my_courses = @courses.created_by(current_staff)
- other_courses = @courses.not_created_by(current_staff)
#creator_dashboard.container
  .menu-header
    = button_tag '', class: 'search-button'
    = text_field_tag :search_term, '', placeholder: 'Filter courses and lessons', class: 'search-bar'
    = button_tag '', class: 'add-button' do
      .tooltiptext Create new course
  .content
    - if my_courses.present?
      .courses-group
        %h4 My courses
        .courses-list
          - my_courses.each_with_index do |course, index|
            .row{ class: "#{index.even? ? 'even' : 'odd'}"}
              .col-all-5
                = course.name
              .col-all-2
                = "#{course.lessons.count} lessons"
              .col-all-2.updated-at
                = date_format(course.updated_at)
              .col-all-1.times
                = '0 times' #todo
              .col-all-2.buttons
                = button_tag '', class: 'view-button'
                = button_tag '', class: 'edit-button'
                = button_tag '', class: 'delete-button'
    - if other_courses.present?
      .courses-group
        %h4 Others
        .courses-list
          - other_courses.each_with_index do |course, index|
            .row{ class: "#{index.even? ? 'even' : 'odd'}"}
              .col-all-6
                = course.name
              .col-all-3
                = "#{course.lessons.count} lessons"
              .col-all-3.updated-at
                = date_format(course.updated_at)