config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :staffs, controllers: {
    registrations: "staffs/registrations"
  }

  devise_for :students, controllers: {
    registrations: "students/registrations",
    sessions: "students/sessions",
    passwords: "students/passwords",
    confirmations: "students/confirmations" }

  resources :students, only: [] do
    resource :dashboards, only: :show, controller: 'students/dashboards'
  end

  root "homes#index"

  get 'dashboards' => 'staffs/dashboards#dashboards'

  resources :courses

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
  has_many :course_instances, dependent: :destroy

  validates :name, :price, :price_period, presence: true

  enum price_period: [:per_day, :per_month]
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :class_room
  belongs_to :staff

  has_many :lessons, dependent: :destroy
  has_many :course_instances, dependent: :destroy

  accepts_nested_attributes_for :lessons

  validates :name, :staff, :price, presence: true

  scope :created_by, -> (staff) { where(staff: staff) }
  scope :not_created_by, -> (staff) { where.not(staff: staff) }
end

app/models/course_instance.rb
class CourseInstance < ActiveRecord::Base
  belongs_to :course
  belongs_to :class_room
  belongs_to :lecture

  has_many :lesson_instances, dependent: :destroy
  has_and_belongs_to_many :students
end

app/models/document.rb
class Document < ActiveRecord::Base
  SUPPORTED_FORMATS = %w(doc pdf docx txt png xls xlsx ai psd odt dxf dwg jpg jpeg gif tiff mpp)

  belongs_to :course

  has_attached_file :file, bucket: ENV['S3_FILES_BUCKET_NAME']
  validates_attachment :file, presence: true,
                       content_type: { content_type: /(#{SUPPORTED_FORMATS.join('|')})/, message: "only #{SUPPORTED_FORMATS.join(', ')} files" }

  def file_name
    File.basename self.file.url(:default, false)
  end
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :course_instances, dependent: :destroy

  enum salary_period: [:per_lesson, :per_course, :per_month]

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course

  has_many :lesson_videos, dependent: :destroy
end

app/models/lesson_instance.rb
class LessonInstance < ActiveRecord::Base
  belongs_to :course_instance
  belongs_to :lesson
end

app/models/lesson_video.rb
class LessonVideo < ActiveRecord::Base
  belongs_to :lesson
end

app/models/redactor.rb
class Redactor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses, dependent: :destroy
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:creator, :accountant, :human_resource_manager]
  enum salary_period: [:per_day, :per_month]

  has_attached_file :avatar, styles: { large: "400x400>", medium: "200x200>", small: "100x100>", thumb: "40x40>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  has_many :courses, dependent: :destroy

  def s3_credentials
    {:bucket => "linhly", :access_key_id => ENV['s3_access_key_id'], :secret_access_key => ENV['s3_secret_access_key']}
  end

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_and_belongs_to_many :courses

  has_attached_file :avatar, styles: { large: "400x400>", medium: "200x200>", small: "100x100>", thumb: "40x40>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
    {:bucket => "linhly", :access_key_id => ENV['s3_access_key_id'], :secret_access_key => ENV['s3_secret_access_key']}
  end

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def first_name
    full_name.split(' ').last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  devise_group :user, contains: [:admin, :student, :staff]

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:full_name, :email, :password, :password_confirmation, :birth_day, :phone_number, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:full_name, :email, :password, :password_confirmation, :current_password, :birth_day, :phone_number, :avatar) }
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def new

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/staffs/dashboards_controller.rb
module Staffs
  class DashboardsController < ApplicationController
    def dashboards
      @courses = filtered_courses
    end

    private

    def filtered_courses
      Course.all
    end
  end
end

app/controllers/students/unlocks_controller.rb
class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message(message)
    case message
      when String
        message.html_safe
      else
        message.to_s
    end
  end

  def random_string(length)
    rand(36**length).to_s(36)
  end

  def currency_format(number)
    number_to_currency(number, unit: 'vnd', precision: 0, format: "%n %u")
  end

  def date_format(time)
    time.strftime('%d/%m/%Y')
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation" class="devise_error_div">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/_flash_message.html.haml
.container.alert-container
  .alert.alert-dismissable{ class: "alert-#{label}"}
    %button(type="button" class="close" data-dismiss="alert" aria-hidden="true") &times;
    = flash_message(message)

app/views/layouts/_flash_messages.html.haml
- if flash.present?
  - flash.each do |label, message|
    = render "layouts/flash_message", label: label, message: message if message.present?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CourseManager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/header'
    = render 'layouts/flash_messages'
    = yield

app/views/shared/_header.html.haml
#header
  #content.container
    #content_row.navbar-collapse.row
      .col-lg-9.col-md-8.col-sm-8.col-xs-6.contact-information
        .have-any-question
          Have any question?
        .phone
          %i.fa-telephone
          %a{href: 'tel:84968220460'} 0968 220 460
        .email
          %i.fa-envelope
          %a{href: 'mailto:support@looneyes.com'} support@looneyes.com
      .col-lg-3.col-md-4.col-sm-4.col-xs-6.account-div
        - if !user_signed_in?
          .col-all-9.register-div
            = link_to "Register", new_registration_path(Student), class: "registration-link"
          .col-all-1.separator
            |
          .col-all-2.login-div
            = render "students/sessions/new"
        - else
          .col-lg-9.col-md-9.col-sm-9.col-xs-9.dropdown.info
            %a.user-name-link.dropdown-toggle{ "data-toggle"=> "dropdown", href: "#" }
              - if current_user.avatar.exists?
                = image_tag current_user.avatar.url(:small)
                = "&nbsp;#{current_user.first_name}".html_safe
              - else
                %span= current_user.full_name
              %span.caret
            %ul.dropdown-menu.bullet.pull-right{ role: "menu" }
              %li
                - if current_user.is_a?(Student)
                  = link_to "edit profile", { controller: "students/registrations", action: "edit" }
                - elsif current_user.is_a?(Staff)
                  = link_to "edit profile", edit_staff_registration_path
              %li.divider
              %li
                = link_to "logout", { controller: "students/sessions", action: "destroy" }, method: :delete
          .col-lg-3.col-md-3.col-sm-3.col-xs-3.notification_icon_div
            %button.notification-button

app/views/shared/_navigation.html.haml
.col-all-12.navigation-div
  .logo-div
  .navigation